server.port=${PORT:8080}
server.address=0.0.0.0

# Conexão Railway
spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ADICIONADO PARA EVITAR ERRO 502 (Health Check)
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
