# Servidor
server.port=${PORT:8080}
server.address=0.0.0.0

# Conexão com Banco
spring.datasource.url=${JDBC_DATABASE_URL:${DATABASE_URL}}
spring.datasource.hikari.connection-init-sql=SELECT 1
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

# FORÇAR RESET DAS TABELAS (Resolve o erro de Long vs String)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Otimização
spring.main.banner-mode=off
management.endpoints.web.exposure.include=health
