# Configurações do Servidor
server.port=${PORT:8080}
server.address=0.0.0.0

# Conexão com o Banco (Com SSL para Nuvem)
spring.datasource.url=${JDBC_URL}?sslmode=require
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações de Banco (Zerar estrutura antiga)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Otimização
spring.main.banner-mode=off
